version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: flexiai-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - flexiai-network

  flexiai-api:
    build:
      context: ../..
      dockerfile: examples/fastapi_multiworker/Dockerfile
    container_name: flexiai-api
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    depends_on:
      redis:
        condition: service_healthy
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --workers 4
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/live"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - flexiai-network
    restart: unless-stopped

volumes:
  redis_data:
    driver: local

networks:
  flexiai-network:
    driver: bridge
