name: Build and Publish Package

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-and-publish:
    name: Build and Upload to GitHub Release
    runs-on: ubuntu-latest  # TODO: Change to [self-hosted, Linux, X64, python36] when runner is available

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: python -m build

      - name: Check distribution
        run: twine check dist/*

      - name: Upload to GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh release upload '${{ github.ref_name }}' dist/** --repo '${{ github.repository }}'
